{"name": "Login with invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Expected Sign-In URL, but got: https://myyatra.finkraft.ai/auth/signin\nassert False", "trace": "self = <tests.test_login.TestLogin object at 0x105754820>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"56cddbf394b53702bad83d60e0c940d7\")>\n\n    @allure.title(\"Login with invalid credentials\")\n    def test_login_invalid_user_details(self, driver):\n        login_page = LoginPage(driver)\n        boolean_result=login_page.login_invalid_details(\"abc@gmail.com\", \"wrongpass\")\n>       assert boolean_result, \\\n       f\"Expected Sign-In URL, but got: {driver.current_url}\"\nE       AssertionError: Expected Sign-In URL, but got: https://myyatra.finkraft.ai/auth/signin\nE       assert False\n\ntest_login.py:36: AssertionError"}, "attachments": [{"name": "test_login_invalid_user_details_2025-06-23_16-24-17.png", "source": "933ef62d-498e-413c-b7c7-a3bd5f589a22-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "74bccedb-8ba1-4c2d-8134-3ee5c2e187d5-attachment.txt", "type": "text/plain"}], "start": 1750676057102, "stop": 1750676057818, "uuid": "b9dcd5d4-e20b-4b24-a7c7-bd735a97ac21", "historyId": "6dc9505648e45d1fa7d0d34aa44c65e4", "testCaseId": "6dc9505648e45d1fa7d0d34aa44c65e4", "fullName": "src.tests.test_login.TestLogin#test_login_invalid_user_details", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "macs-MacBook-Pro.local"}, {"name": "thread", "value": "87558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_login"}]}