{"name": "Scroll down dashboard page till the end", "status": "passed", "steps": [{"name": "Login to the application", "status": "passed", "steps": [{"name": "Enter email and password and click Sign In.", "status": "passed", "parameters": [{"name": "username", "value": "'sumit@kgrp.in'"}, {"name": "password", "value": "'HRzyUJi0'"}], "start": 1752140936570, "stop": 1752140947352}], "start": 1752140936570, "stop": 1752140947352}, {"name": "Wait for dashboard to load", "status": "passed", "start": 1752140947352, "stop": 1752140952353}, {"name": "Scroll the scrollable dashboard container to bottom", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/src/tests/test_dashboard.py\", line 117, in test_scroll_to_bottom_of_dashboard\n    dashboard_page.scroll_element_by_selector(\"#ZDBSampleDivForDataSheet\")\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/src/pages/dashboard_page.py\", line 297, in scroll_element_by_selector\n    self.switch_to_dashboard_iframe()\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/src/pages/dashboard_page.py\", line 59, in switch_to_dashboard_iframe\n    iframe = self.driver.find_element(*self.IFRAME_LOCATOR)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 917, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 446, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/util/retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/util/util.py\", line 38, in reraise\n    raise value.with_traceback(tb)\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 534, in _make_request\n    response = conn.getresponse()\n  File \"/Users/sumit/PycharmProjects/PartnerPortalUI/.venv/lib/python3.9/site-packages/urllib3/connection.py\", line 516, in getresponse\n    httplib_response = super().getresponse()\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 1349, in getresponse\n    response.begin()\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py\", line 285, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\n"}, "start": 1752140952353, "stop": 1752140954559}], "start": 1752140936569, "stop": 1752140954593, "uuid": "a5bb1765-290d-45a2-9c1b-539c91ee8f47", "testCaseId": "9b81d0e057fd07827c2c18fce54c41b1", "fullName": "src.tests.test_dashboard.TestDashBoard#test_scroll_to_bottom_of_dashboard"}