{"name": "Login with invalid credentials", "status": "passed", "attachments": [{"name": "log", "source": "87004ad9-1313-4257-9cbe-8f26e51bbf43-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "27c8ad0e-5c39-487f-84b9-9e642196106b-attachment.txt", "type": "text/plain"}], "start": 1751522395022, "stop": 1751522395515, "uuid": "02bdeb73-fb35-4224-95f9-df9a720fd489", "historyId": "6dc9505648e45d1fa7d0d34aa44c65e4", "testCaseId": "6dc9505648e45d1fa7d0d34aa44c65e4", "fullName": "src.tests.test_login.TestLogin#test_login_invalid_user_details", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "macs-MacBook-Pro.local"}, {"name": "thread", "value": "5334-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_login"}]}